site_name: qttools
site_url: https://vincent-maillou.github.io/qttools/

repo_url: https://github.com/vincent-maillou/qttools

theme:
  name: material
  palette:
    primary: default
  font:
    text: Arimo
    code: Fira Code
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/generate_api_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.python.org/3/objects.inv
          options:
            # General options
            show_source: false
            # Headings options
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # Members options
            members_order: "source"
            filters: [] # show all members
            # Docstring options
            docstring_style: "numpy"
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            # Signatures options

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Quick Start: getting_started/quick_start.md
  - User Guide:
      - qttools: user/index.md
  - API Reference: reference/
